### ISSUE TITLE
Missing Node.js 15 support

### ISSUE THREAD

**Issue by jens-duttke** [sounisi5011/package-version-git-tag#156]
I'm using Node.js `15.8.0` and the installation fails with:
```
error package-version-git-tag@3.0.0: The engine "node" is incompatible with this module. Expected version "10.x || 12.x || 14.x". Got "15.8.0"
error Found incompatible module.
```

I can hardly imagine that a new Node.js version could break the functionality of this package. Is it really necessary to limit the maximum Node.js version?

**Comment by sounisi5011** [comment]
Sorry for neglecting this project for so long.

You are correct, this CLI is probably still available in Node.js 15.
At the time I was developing this CLI, I intended to maintain it on an ongoing basis going forward.
So I specified only the versions I tested reliably in the `engines.node` field.

Currently, I do not use this CLI myself (for example, I use [`shipjs`](https://www.npmjs.com/package/shipjs) or [`release-please-action`](https://github.com/google-github-actions/release-please-action) instead).
Therefore, I rarely maintain this CLI anymore.
I will try to include the new Node.js in the `engines.node` field after the next release.

However, as of March 8, 2023, [Node.js 15 is End-of-Life](https://github.com/nodejs/Release/tree/54e615d89bf2e056644e138e7e33714bfd1b67ee#end-of-life-releases).
I am sincerely sorry, but Node.js 15 will not be supported.

If you want to use this CLI with Node.js 15, please use the yarn `--ignore-engines` option.
